// ce fichier est éxécuté en postInstall et va générer les fichiers
// * package.json avec les plugins déclarés en config
// * generatedDisplays.js pour l'import dynamique des display par plugin
//   (cf https://webpack.js.org/guides/code-splitting/#dynamic-imports)
// * generatedEditors.js qui exporte un gros objet avec tous les éditeurs
// * icons.js qui exporte toutes les icones (utilisé par le plugin arbre qui a besoin des icones des autres)

const fs = require('fs')
const path = require('path')
const {plugins, external} = require('./plugins')

const me = path.basename(__filename)
const comment = `dynamically generated by ${me} on postinstall`

/**
 * Retourne une string avec la liste des imports et une var plugins qui les contient
 * @private
 * @param {string} suffix etitor|icon
 * @return {string}
 */
const getImports = (suffix) => {
  return plugins.map((plugin, index) => `import * as plugin${index} from '${plugin}/${suffix}'\n`).join('') + '\n' +
    `const plugins = [${plugins.map((plugin, index) => `plugin${index}`).join(', ')}]`
}

// package.json
const packageContent = {
  license: 'UNLICENSED',
  comment,
  dependencies: external
}
fs.writeFileSync('./package.json', JSON.stringify(packageContent, null, 2))

// generatedDisplays
const displays = `// ${comment}
${plugins.map((plugin, index) => `import type${index} from '${plugin}/type'`).join('\n')}

const displays = {}

${plugins.map((plugin, index) => `displays[type${index}] = () => import('${plugin}/display')`).join('\n')}

export default displays
`
fs.writeFileSync('./generatedDisplays.js', displays)

// generatedEditors
const editors = `// ${comment}
${getImports('editor')}

const editors = {}

plugins.forEach(({type, ...others}) => {
  editors[type] = others
})

export default editors
`
fs.writeFileSync('./generatedEditors.js', editors)

// icons
const icons = `// ${comment}
${getImports('icon')}

const icons = {}

plugins.forEach(({type, icon}) => {
  icons[type] = icon
})

export default icons
`
fs.writeFileSync('./icons.js', icons)
