const fs = require('fs')
const path = require('path')
const {plugins, external} = require('./plugins')

const me = path.basename(__filename)
const comment = `dynamically generated by ${me} on postinstall`

// ce fichier est éxécuté en postInstall et va générer les fichiers
// * package.json avec les plugins déclarés en config
// * displays.js pour l'import dynamique des display par plugin
//   (cf https://webpack.js.org/guides/code-splitting/#dynamic-imports)
// * editors.js qui exporte un gros objet avec tous les éditeurs
// * icons.js qui exporte toutes les icones

const packageContent = {
  license: 'UNLICENSED',
  comment,
  dependencies: external
}

fs.writeFileSync('./package.json', JSON.stringify(packageContent, null, 2))

const getImports = (suffix) => {
  return plugins.map((plugin, index) => `import * as plugin${index} from '${plugin}/${suffix}'\n`).join('') + '\n' +
  `const plugins = [${plugins.map((plugin, index) => `plugin${index}`).join(', ')}]`
}

const displays = `// ${comment}
${plugins.map((plugin, index) => `import type${index} from '${plugin}/type'`).join('\n')}

const displays = {}

${plugins.map((plugin, index) => `displays[type${index}] = () => import('${plugin}/display')`).join('\n')}

export default displays
`

const editors = `// ${comment}
${getImports('editor')}

const editors = {}

plugins.forEach(({type, ...others}) => {
  editors[type] = others
})

export default editors
`

const icons = `// ${comment}
${getImports('icon')}

const icons = {}

plugins.forEach(({type, icon}) => {
  icons[type] = icon
})

export default icons
`

fs.writeFileSync('./generatedDisplays.js', displays)
fs.writeFileSync('./generatedEditors.js', editors)
fs.writeFileSync('./icons.js', icons)
