// ce fichier est éxécuté en postInstall et va générer les fichiers
// * package.json avec les plugins déclarés en config
// * generatedDisplays.js pour l'import dynamique des display par plugin
//   (cf https://webpack.js.org/guides/code-splitting/#dynamic-imports)
// * generatedEditors.js qui exporte un gros objet avec tous les éditeurs
// * icons.js qui exporte toutes les icones (utilisé par le plugin arbre qui a besoin des icones des autres)

const fs = require('fs')
const path = require('path')
const {pluginsPaths, external} = require('./plugins')
// pour external, si y'a une version dans les peerDependencies du package.json de l'appli c'est ça qu'on utilise
const {peerDependencies} = require('../../package')

const me = path.basename(__filename)
const comment = `dynamically generated by ${me} on postinstall`

/**
 * Retourne une string avec la liste des imports et une var plugins qui les contient
 * @private
 * @param {string} suffix etitor|icon
 * @return {string}
 */
const getImports = (suffix) => {
  return pluginsPaths.map((pluginPath, index) => `import * as plugin${index} from '${pluginPath}/${suffix}'\n`).join('') + '\n' +
    `const plugins = [${pluginsPaths.map((pluginPath, index) => `plugin${index}`).join(', ')}]`
}

// package.json
const dependencies = {}
Object.entries(external).forEach(([module, path]) => {
  if (path === true) {
    if (peerDependencies[module]) dependencies[module] = peerDependencies[module]
    else throw Error(`Le plugin ${module} est demandé dans la configuration sans préciser son origine et il n’existe pas dans les peerDependencies de cette sésathèque`)
  } else {
    dependencies[module] = path
  }
})

const packageContent = {
  license: 'UNLICENSED',
  comment,
  dependencies
}
fs.writeFileSync('./package.json', JSON.stringify(packageContent, null, 2))

// generatedDisplays
const displays = `// ${comment}
${pluginsPaths.map((pluginPath, index) => `import type${index} from '${pluginPath}/type'`).join('\n')}

const displays = {}

${pluginsPaths.map((pluginPath, index) => `displays[type${index}] = () => import('${pluginPath}/display')`).join('\n')}

export default displays
`
fs.writeFileSync('./generatedDisplays.js', displays)

// generatedEditors
const editors = `// ${comment}
${getImports('editor')}

const editors = {}

plugins.forEach(({type, ...others}) => {
  editors[type] = others
})

export default editors
`
fs.writeFileSync('./generatedEditors.js', editors)

// icons
const icons = `// ${comment}
${getImports('icon')}

const icons = {}

plugins.forEach(({type, icon}) => {
  icons[type] = icon
})

export default icons
`
fs.writeFileSync('./icons.js', icons)
