version: '2'
services:
  mongo-global:
    image: mongo
    ports:
      - 3312:27017

  mongo-private:
    image: mongo
    ports:
      - 3313:27017

  app-global:
    build: ./docker/node
    ports:
      - 3001:3001
    volumes:
      - .:/app
    links:
      - mongo-global
      - redis
    command: npm run start:dev

  app-private:
    build: ./docker/node
    ports:
      - 3003:3003
    volumes:
      - .:/app
    links:
      - mongo-private
      - redis
    command: npm run start:devcommun

  redis:
    image: redis
