version: '2'
services:
  mongo:
    image: mongo
  redis:
    image: redis

  sesatheque:
    build: ./docker/sesatheque
    ports:
      - 3001:3001
    volumes:
      # on pourrait exporter toute la racine sauf des dossier à lister dans .dockerignore
      # mais on veut _private sous le nom _privateLocal, et lister ce qu'on prend
      # est pas plus long que de lister ce que l'on exclu…

      # on exporte notre _private sous un autre nom
      - ./_private:/sesatheque/_privateLocal
      # le private du docker qui va récupérer le précédent et surcharger le minimum imposé par ce docker-compose
      - ./docker/sesatheque/_private:/sesatheque/_private
      # le reste dont l'appli a besoin
      - ./app:/sesatheque/app
      - ./logs:/sesatheque/logs
      - ./package.json:/sesatheque/package.json
      - ./scripts:/sesatheque/scripts
      - ./tasks:/sesatheque/tasks
      - ./webpack.config.js:/sesatheque/webpack.config.js
      - ./webpackConfigLoader.js:/sesatheque/webpackConfigLoader.js
      - ./webpackThrowLoader.js:/sesatheque/webpackThrowLoader.js
      - ./yarn.lock:/sesatheque/yarn.lock

    links:
      - mongo
      - redis
    command: "./scripts/wait-for-it.sh mongo:27017 -t 30 --strict -- yarn run docker:_start"

  test:
    build: ./docker/sesatheque
    environment:
      - SESATHEQUE_CONF=test
    ports:
      - 3011:3011
    volumes:
      # on pourrait exporter toute la racine sauf des dossier à lister dans .dockerignore
      # mais on veut _private sous le nom _privateLocal, et lister ce qu'on prend
      # est pas plus long que de lister ce que l'on exclu…

      # on exporte notre _private sous un autre nom
      - ./_private:/sesatheque/_privateLocal
      # le private du docker qui va récupérer le précédent et surcharger le minimum imposé par ce docker-compose
      - ./docker/sesatheque/_private:/sesatheque/_private
      # le reste dont l'appli a besoin
      - ./app:/sesatheque/app
      - ./logsTest:/sesatheque/logsTest
      - ./package.json:/sesatheque/package.json
      - ./scripts:/sesatheque/scripts
      - ./tasks:/sesatheque/tasks
      - ./test:/sesatheque/test
      - ./webpack.config.js:/sesatheque/webpack.config.js
      - ./webpackConfigLoader.js:/sesatheque/webpackConfigLoader.js
      - ./webpackThrowLoader.js:/sesatheque/webpackThrowLoader.js
      - ./yarn.lock:/sesatheque/yarn.lock

    links:
      - mongo
      - redis
    command: "./scripts/wait-for-it.sh mongo:27017 -t 30 --strict -- yarn run docker:_test"
