version: '2'
services:
  mongo-global:
    image: mongo
    ports:
      - 3312:27017

  mysql-global:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sesatheque
      MYSQL_USER: sesatheque
      MYSQL_PASSWORD: sesatheque

  mongo-private:
    image: mongo
    ports:
      - 3313:27017

  mysql-private:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stcommun
      MYSQL_USER: stcommun
      MYSQL_PASSWORD: stcommun

  app-global:
    build: ./docker/node
    ports:
      - 3001:3001
    volumes:
      - .:/app
    links:
      - mysql-global
      - mongo-global
      - memcache
    command: npm run start:dev

  app-private:
    build: ./docker/node
    ports:
      - 3003:3003
    volumes:
      - .:/app
    links:
      - mysql-private
      - mongo-private
      - memcache
    command: npm run start:devcommun

  memcache:
    image: memcached
