version: '2'
services:
  # https://github.com/docker-library/official-images/blob/master/library/mongo
  mongo:
    image: mongo:4.0

  # https://github.com/docker-library/official-images/blob/master/library/redis
  redis:
    image: redis:3.2

  sesatheque:
    build: ./docker/sesatheque
    ports:
      - 3001:3001
    volumes:
      # on pourrait exporter toute la racine sauf des dossier à lister dans .dockerignore
      # mais on veut _private sous le nom _privateLocal, et lister ce qu'on prend
      # est pas plus long que de lister ce que l'on exclu…

      # on exporte notre _private sous un autre nom
      - ./_private:/home/app/sesatheque/_privateLocal
      # le private du docker qui va récupérer le précédent et surcharger le minimum imposé par ce docker-compose
      - ./docker/sesatheque/_private:/home/app/sesatheque/_private
      - .:/home/app/sesatheque
      - ~/.cache/yarn:/home/app/.cache/yarn

    links:
      - mongo
      - redis
    command: "./scripts/wait-for-it.sh mongo:27017 -t 30 --strict -- yarn run docker:_start"

  test:
    build: ./docker/sesatheque
    environment:
      - SESATHEQUE_CONF=test
    ports:
      - 3011:3011
    volumes:
      # on pourrait exporter toute la racine sauf des dossier à lister dans .dockerignore
      # mais on veut _private sous le nom _privateLocal, et lister ce qu'on prend
      # est pas plus long que de lister ce que l'on exclu…

      # on exporte notre _private sous un autre nom
      - ./_private:/home/app/sesatheque/_privateLocal
      # le private du docker qui va récupérer le précédent et surcharger le minimum imposé par ce docker-compose
      - ./docker/sesatheque/_private:/home/app/sesatheque/_private
      # On a pas besoin de build en test
      # le reste dont l'appli a besoin
      - .:/home/app/sesatheque
      - ~/.cache/yarn:/home/app/.cache/yarn

    links:
      - mongo
      - redis
    command: "./scripts/wait-for-it.sh mongo:27017 -t 30 --strict -- yarn run docker:_test"
