version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 3312:27017

  app:
    build: ./docker/node
    ports:
      - 3001:3001
    volumes:
      - .:/app
    links:
      - mongo
      - redis
    command: npm run start:dev

  redis:
    image: redis
