#! /bin/bash

function build_scripts() {
  step "Construction des scripts"
  indexify 'require("./$$");' source/client/_modules.js '**/index.js'
  indexify 'require("./$$");' source/server/_modules.js '**/index.js'
  script-builder --debug=$DEBUG source/client/app.js public/app.js
}

function build_styles() {
  step "Construction des styles"
  indexify '@import "$$";' source/styles/_styles.scss '../server/**/styles.scss' '../client/**/styles.scss' './*/**/*.scss'
  style-builder --debug=$DEBUG source/styles/app.scss public/app.css
}

function clean() {
  rm -rf {documentation,node_modules,public/app.*}
}

function prepare() {
  npm install > /dev/null
}

function build() {
  build_styles
  build_scripts
}

function reset() {
  clean && prepare && build
}

# initialisation de nos constantes et fct communes, si ce n'a pas déjà été fait
[ -z "${STAGE-}" ] && . $(dirname $0)/app_init_vars

init_command $@
$COMMAND

