#!/bin/bash

function build_scripts() {
  echo "Construction des scripts"
  (cd source/client; find . -mindepth 1 -name "index.js"  | sed -E 's/^(.+)/require("\1");/' | sort > _modules.js)
  (cd source/server; find . -mindepth 1 -name "index.js"  | sed -E 's/^(.+)/require("\1");/' | sort > _modules.js)
  node_modules/.bin/browserify source/client/app.js > public/app.js
}

function build_styles() {
  echo "Construction des styles"
  (cd source/styles; find .. -mindepth 1 -name "styles.scss"  | sed -E 's/^(.+)/@import "\1";/' | sort > _styles.scss)
  node_modules/.bin/node-sass source/styles/app.scss | \
    node_modules/.bin/postcss --use autoprefixer > public/app.css
}

function clean() {
  rm -rf {documentation,node_modules,public/app.*}
}

function prepare() {
  [[ ! -d node_modules ]] && npm install
}

function build() {
  prepare
  build_styles
  build_scripts
}

function reset() {
  clean && build
}

cd (dirname $0)/..
reset
cd -
