#!/bin/bash

set -u

dirInitial="$PWD"
dirApp=$(dirname $0)/../

function fin() {
  cd "$dirInitial"
}

function usage() {
  local exitCode=${1:-0}
  echo "Lance la génération de la documentation"
  echo "Une option obligatoire parmi"
  echo "  -a : toutes les documentations"
  echo "  -h : afficher cette aide"
  echo "  -l : documentation de lassi"
  echo "  -p : documentation des plugins"
  echo "  -r : documentation de l'api REST"
  echo "  -s : documentation du code serveur"
  exit $exitCode
}

function go() {
  local cas=$1
  echo -n "$cas "
  $jsdoc -c jsdoc/jsdoc$cas.json && echo "ok" || echo "KO"
}
# on veut exécuter fin avant de sortir
trap fin EXIT

cd "$dirApp"

# sans options on l'aide
[ $# -lt 1 ] && usage

# vérif de jsdoc
jsdoc=node_modules/.bin/jsdoc
[ ! -x $jsdoc ] && echo "$jsdoc n'est pas exécutable" >&2 && exit 1

# check des options
while getopts "achlprs" OPTION
do
  case $OPTION in
    a) for f in jsdoc/jsdoc*.json; do cas=$(basename ${f/jsdoc\/jsdoc/} .json); go $cas; done;;
    c) go ModuleSesathequeClient;;
    h) usage;;
    l) go Lassi;;
    p) go Plugins;;
    r) go RestApi;;
    s) go App;;
    *) usage 1;;
  esac
done

# et si on passe directement un nom en arg
if [ $# -gt 0 ]; then
  for arg in $@
  do
    # on prend tous les arguments sauf les options
    [ ${arg:0:1} != "-" ] && go $arg
  done
fi

fin
