#!/bin/bash

set -u

dirInitial="$PWD"

function fin() {
  cd "$dirInitial"
}

function usage() {
  local exitCode=${1:-0}
  echo "Compile require.js avec notre config"
  exit $exitCode
}

# on veut exécuter fin avant de sortir
trap fin EXIT

[ "${1:-}" == "-h" -o "${1:-}" == "--help" ] && usage

dirRoot="$(dirname $0)/.."
cd $dirRoot

// cette écriture permet de mettre dans du js inline require('sesatheque-client')
node_modules/.bin/browserify -r sesatheque-client > app/ressource/public/sesatheque-client.js
node_modules/.bin/uglifyjs app/ressource/public/apiClient.js --compress --mangle > app/ressource/public/sesatheque-client.min.js

exit 0

tmp=/tmp/$(basename $0)
src=node_modules/requirejs/require.js
dst=appmain/public/vendors/requirejs/require.min.js
echo -n "$dst "
# on récupère la conf sans le define de fin qui n'aime pas être concaténé tel quel
sed -e '/BEGIN CUT/, /END CUT/ d; s@// IF CUT@@g;' app/ressource/public/initRequire.js > $tmp
node_modules/.bin/uglifyjs $src $tmp --compress --mangle > $dst && echo ok || echo KO
rm -f $tmp
# d'autres js à minifier
src=node_modules/sesatheque-client/index.js
dst=app/ressource/public/vendors/sesamath/sesatheque-client/index.min.js
echo -n "module npm sesatheque-client => $dst "
node_modules/.bin/uglifyjs $src --compress --mangle > $dst && echo ok || echo KO
