#!/bin/bash

set -u

dirInitial="$PWD"

function fin() {
  cd "$dirInitial"
}

function usage() {
  local exitCode=${1:-0}
  echo "Compile notre css à partir de app/staticStylesSrc/page.less"
  exit $exitCode
}

# on veut exécuter fin avant de sortir
trap fin EXIT

cd $(dirname $0)/../
dirApp=$PWD
cd "app/staticStylesSrc"

# sans options on lance en dev
#lessc --clean-css="--s1 --advanced --compatibility=ie8" --include-path="app/main/public/styles:app/main/public/vendors/knacss/less" app/main/public/styles/page.less app/main/public/styles/page.css \
#./node_modules/.bin/lessc --clean-css="--compatibility=ie8" --include-path="app/main/public/styles:app/main/public/vendors/knacss/less" --source-map=app/main/public/styles/page.map app/main/public/styles/page.less app/main/public/styles/page.css \
$dirApp/node_modules/less/bin/lessc --clean-css="--compatibility=ie8" --source-map=page.map page.less page.css \
  && $dirApp/node_modules/less/bin/lessc --clean-css="--compatibility=ie8" --source-map=iframe.map iframe.less iframe.css \
  && echo "OK" \
  || echo "KO"
