#!/bin/bash

set -u

dirInitial="$PWD"

function fin() {
  cd "$dirInitial"
}

function usage() {
  local exitCode=${1:-0}
  echo "Compile notre css à partir de app/staticStylesSrc/page.less"
  exit $exitCode
}

# on veut exécuter fin avant de sortir
trap fin EXIT

cd $(dirname $0)/../
dirApp=$PWD
LESSC="$dirApp/node_modules/less/bin/lessc"
cd "$dirApp/app/server/src/styles"

# sans options on lance en dev
$LESSC --clean-css="--compatibility=ie8" --source-map=page.map page.less page.css \
  && $LESSC --clean-css="--compatibility=ie8" --source-map=iframe.map iframe.less iframe.css \
  && echo "OK" \
  || echo "KO"
