#!/bin/bash

usage() {
  echo "$0 [file]"
  echo 'Ouvre un shell mongo ou exécute un script mongo.'
  echo 'Sans argument ça ouvre un shell en chargeant scripts-mongo/mongorc.js au préalable'
  echo '(qui ajoute plusieurs fonctions utile dans un contexte sesalab, cf source pour le détail)'
  echo
  echo 'Options :'
  echo '  -c <collection> : indique une collection (pour -i ou -x, si le nom du fichier ne l’indique pas)'
  echo '  -d <dossier> : pour traiter tous les fichiers *.export qu’il contient'
  echo '  -e <string> : évalue <string> dans le scope du script (ex `-e "var foo = 42"` pour avoir la variable foo dans le script)'
  echo '  -f <fichier> : fichier à utiliser (script ou import ou export)'
  echo '  -g <fichier> : fichier (path absolu) de conf de l’appli (à prendre à la place de _private/config.js)'
  echo '  -h : affiche cette aide'
  echo '  -i : lance mongoimport sur le fichier (collection déduite si -c absent) ou tous les fichiers de -d (sauf staging prod)'
  echo '  -p : affiche seulement les arguments mongo'
  echo '  -q : mode --quiet'
  echo '  -s : ajoute --shell, pour charger un ou des scripts et récupérer un shell ensuite'
  echo '  -u : mode --upsert à la place de --drop pour les imports'
  echo '  -x : avec -c, lance mongoexport vers le fichier (-f), sans exporte toutes les collections vers des fichiers du dossier -d'
  echo
  echo 'exemple d’export vers des fichiers ~/tmp/sesalab.YYYY-MM-JJ/collxxx.export :'
  echo "$0 -x -d ~/tmp/bibliotheque"'.$(date +%F)/'
  echo
  echo 'exemple d’import, avec des fichiers ~/tmp/sesalab.2017-10-30/collxxx.export :'
  echo './scripts/mongoApp -i -d ~/tmp/sesalab.2017-10-30/'
  exit $1
}

rootDir=$(dirname $0)/..
nodeConf="$rootDir/_private/config.js"

jsCode=''
staging=''
collection=''
dir=''
file=''
isImport=No
isExport=No
isQuiet=No
isUpstert=No
justPrint=No
forceShell=No

# check des options
while getopts "c:d:e:f:g:hipqsx" OPTION
do
  case $OPTION in
    c) collection=$OPTARG;;
    d) dir=$OPTARG;;
    e) jsCode="$OPTARG";;
    f) file="$OPTARG";;
    g) nodeConf="$OPTARG";;
    h) usage 0;;
    i) isImport=Yes ;;
    p) justPrint=Yes;;
    q) isQuiet=Yes;;
    s) forceShell=Yes;;
    u) isUpsert=Yes;;
    x) isExport=Yes ;;
  esac
done

# pass en dernier car il peut contenir des espaces
read -r staging host port db user pass <<< $(node -e "const c = require('$nodeConf'); const d = c.\$entities.database; console.log(\`\${c.application.staging} \${d.host} \${d.port} \${d.name}\ \${d.user} '\${d.password}'\`)")

# check des variables
[ -z "$host" ] && echo "pas trouvé host dans $nodeConf">&2 && usage 1
[ -z "$port" ] && echo "pas trouvé port dans $nodeConf">&2 && usage 1
[ -z "$user" ] && echo "pas trouvé user dans $nodeConf">&2 && usage 1
[ -z "$pass" ] && echo "pas trouvé pass dans $nodeConf">&2 && usage 1
[ -z "$db" ] && echo "pas trouvé db dans $nodeConf">&2 && usage 1
# $pass contient déjà les single quotes
args="--host $host --port $port -u $user -p $pass"

[ "$isQuiet" == 'Yes' ] && args="$args --quiet"
# si on précise pas de fichier et que c'est ni import ni export, ce sera un shell,
# on ajoute ici nos fonctions par défaut
if [ "$isImport" == "No" ] && [ "$isExport" == "No" ] && [ -z "$file" ]; then
  file="$rootDir/scripts-mongo/mongorc.js"
  forceShell=Yes
fi

[ "$forceShell" == 'Yes' ] && args="$args --shell"
[ "$justPrint" == 'Yes' ] && echo "mongo(import|export) $args (--db $db) …" && exit 0

if [ "$isImport" == "Yes" ]; then
  [ "$staging" == "prod" ] && echo 'Import en production impossible (mettre config.application.staging=dev ou -pre-prod- pour le forcer)'>&2 && usage 1
  [ "$isUpsert" == "Yes" ] && args="--upsert $args --db $db" || args="--drop $args --db $db"
  # On précise un fichier
  if [ -n "$file" ]; then
    if [ -z "$collection" ]; then
      eval mongoimport $args --file  $file
    else
      eval mongoimport $args --file  $file --collection $collection
    fi
  elif [ -n "$dir" ]; then
    [ -n "$collection" ] && echo 'Si vous précisez une collection il faut préciser le fichier'>&2 && usage 1
    for file in $dir/*.export; do
      echo "import $file"
      eval mongoimport $args --file $file
    done
  else
    echo "Il faut indiquer un dossier ou un fichier pour importer">&2 && usage 1
  fi

elif [ "$isExport" == "Yes" ]; then
  [ -z "$dir" ] && [ -z "$file" ] && echo "Il faut indiquer un dossier ou un fichier pour exporter">&2 && usage 1
  if [ -n "$collection" ]; then
    [ -z "$file" ] && file="$dir/$collection.export"
    eval mongoexport $args --db $db --collection $collection > $file
  else
    # toutes les collections
    [ -z "$dir" ] && echo "Il faut indiquer dossier pour l'export si vous ne précisez pas de collection">&2 && usage 1
    for collection in $(echo 'show collections'|eval mongo --quiet $args $db); do
      file="$dir/$collection.export"
      echo "Collection $collection dans $dir/$collection.export"
      eval mongoexport $args --db $db --collection $collection > $file
    done
  fi

elif [ -n "$jsCode" ]; then
  eval mongo --eval "\"$jsCode\"" $args $db $file

else
  eval mongo $args $db $file
fi
