#!/bin/bash

set -u

dirInitial="$PWD"
dirApp=$(dirname $0)/../
PM2=app/_private/pm2App.json5
nodeEnv=${NODE_ENV:-dev}
pm2opts=''
OK=0
KO=1

function fin() {
  cd "$dirInitial"
}

function usage() {
  local exitCode=${1:-0}
  echo "Lance ou recharge l'application (en mode dev par défaut)"
  echo "option facultative"
  echo "  -c : pour indiquer un autre fichier de conf pm2 que $PM2 (à mettre avant les actions)"
  echo "  -d : lancement avec $PM2 en mode dev (rappeler le script à l'identique pour recharger, avec -x pour arrêter)"
  echo "  -h : afficher cette aide"
  echo "  -n : lancement avec node directement en mode dev"
  echo "  -o : pour passer des options à pm2 (à mettre avant les actions)"
  echo "  -p : lancement avec $PM2 en mode prod (rappeler le script à l'identique pour recharger, avec -x pour arrêter)"
  echo "  -x : arrête les process pm2 sesatheque qui pourraient tourner"
  echo "  -w : lancement avec $PM2 en mode dev avec watch + logs"
  exit $exitCode
}

function getConf() {
  [ $# -lt 1 ] && return 1
  local default="${2:-}"
  local value="$(sed -nre "s/^[^#]*$1[ \"':\t]+([^\"',]+).*/\1/p;" $PM2 |head -1)"
  [ -z "$value" ] && value="$default"
  echo $value
}

function del() {
  local name="$(getConf name sesatheque)"
  pm2 delete $name
  exit $?
}

function runNode() {
  NODE_ENV=$nodeEnv node --stack_trace_limit=50 app/index.js
}

function runPm2() {
  [ ! -f "$PM2" ] && echo "le fichier $PM2 n'existe pas" >&2 && usage 1
  pm2 startOrRestart $PM2 --env $nodeEnv $pm2opts
  exit $?
}

function runPm2Watch() {
  [ ! -f "$PM2" ] && echo "le fichier $PM2 n'existe pas" >&2 && usage 1
  local cmd="pm2 startOrRestart $PM2 --env watch"
  echo $cmd
  eval $cmd
  local retour=$?
  echo -e "\nCtrl+c pour arrêter les logs (mais pas pm2), pm2 logs pour les relancer\n"
  #pm2 logs &
  exit $retour
}

# on veut exécuter fin avant de sortir
trap fin EXIT

cd "$dirApp"

# sans options on lance en dev
[ $# -lt 1 ] && nodeEnv='dev' && runPm2

# check des options
while getopts "c:dhno:pxw" OPTION
do
  case $OPTION in
    c) PM2="$OPTARG";;
    d) nodeEnv='dev'; runPm2;; # on laisse NODE_ENV tel qu'il est dans l'environnement mais on impose dev
    h) usage;;
    n) runNode;;
    o) pm2opts="$OPTARG";;
    p) nodeEnv='prod'; runPm2;;
    x) del;;
    # les options passées en ligne de commande n'écrasent pas celle de la conf
    # en cli le scale sert à rien avec --watch (et donne une erreur à partir de pm2 1.0)
    # pas réussi à faire un env watch qui marche pour avoir du watch dans ce cas mais pas en prod,
    # on passe par un fichier de conf distinct
    w) nodeEnv='dev'; PM2=${PM2/.json5/Watch.json5}; runPm2;;
    *) usage 1;;
  esac
done
